language: node_js
node_js:
  - 11

dist: trusty
sudo: false
cache: yarn

branches:
  only:
    - production
    - master

stages:
  - name: Test
  - name: Check Bundlesize
    if: NOT branch = production

jobs:
  include:
    - stage: Test
      script: yarn test
    - stage: Check Bundlesize
      script: 
        - yarn build
        - yarn bundlesize